const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Frontend',
      link: {type: 'generated-index', title: 'Frontend'},
      items: [{type: 'autogenerated', dirName: 'frontend'}],
    },
    {
      type: 'category',
      label: 'Backend',
      link: {type: 'generated-index', title: 'Backend'},
      items: [{type: 'autogenerated', dirName: 'backend'}],
    },
    {
      type: 'category',
      label: 'AI Service',
      link: {type: 'generated-index', title: 'AI Service'},
      items: [{type: 'autogenerated', dirName: 'ai-service'}],
    },
    {
      type: 'category',
      label: 'Shared Contracts',
      link: {type: 'generated-index', title: 'Shared Contracts'},
      items: [{type: 'autogenerated', dirName: 'shared-contracts'}],
    },
  ],
};

export default sidebars;
